# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('houses', '0004_auto_20161215_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='region',
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.ManyToManyField(to='regions.Region'),
        ),
    ]
