# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20161215_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='region',
            field=models.ManyToManyField(related_name='house_region', to='regions.Region'),
        ),
    ]
